// Code generated by mockery v2.14.0. DO NOT EDIT.

//go:build !codeanalysis
// +build !codeanalysis

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	types "example/types"
)

// Hotels is an autogenerated mock type for the Hotels type
type Hotels struct {
	mock.Mock
}

// GetHotelByName provides a mock function with given fields: ctx, name
func (_m *Hotels) GetHotelByName(ctx context.Context, name string) (types.Hotel, error) {
	ret := _m.Called(ctx, name)

	var r0 types.Hotel
	if rf, ok := ret.Get(0).(func(context.Context, string) types.Hotel); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(types.Hotel)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetHotels provides a mock function with given fields: ctx
func (_m *Hotels) GetHotels(ctx context.Context) ([]types.Hotel, error) {
	ret := _m.Called(ctx)

	var r0 []types.Hotel
	if rf, ok := ret.Get(0).(func(context.Context) []types.Hotel); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Hotel)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewHotels interface {
	mock.TestingT
	Cleanup(func())
}

// NewHotels creates a new instance of Hotels. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHotels(t mockConstructorTestingTNewHotels) *Hotels {
	mock := &Hotels{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
